names = """Apiplayground
Application
Async
B2B
Central-ops-app-01
Central-ops-app-02
Checkoutx
Coherence-Backend
Compulsive
daas-admin-app
Dev-Ssot-Airflow-App-01
Dev-Ssot-ML-Analytics-App-01
Dev-Ssot-ML-Analytics-App-02
Dynatrace
Eftnet
Enach
FBRI-SLA-01-azn
gitlab
GlobalPayments
GlobalPaymentsIntegration
IndigoOmni
inquiry-data
InternalInfo
Invoicing
IrctcIndus
Jocata
Jumphost
marvel-client
ML-Analytics-New-01
ML-CreditAnalytics-app01
Morpheus
OmniChannel
OneAdmin
Payout-Recon
payuDB-slave
prod-asi-admin--asg
prod-asi-app--asg
prod-jkcc-app1
Prod-obriskscore-app-new01
Prod-PgSelector-Logstash
Prod-SwitchPay-Logstash
ProdResellerAmazonLinuxApp
ProdResellerAmazonLinuxBG
ProxyService01-azn
ProxyService02-azn
Recommendationengine
redash
redash-amz-linux
redash-new
refund-scala
RIntegration
RiskMicroservice
rto-admin
Sarc
Securepayments
Securepayments-PythonJob
SFTP01
slave-db-all-application
SMB-Analytics
Snorkel
Snorkel-HDFC
SolutionsLogBackup
sonarqube
Srt-monitor
Storecard
Trident-Maxwell-payuhash01-amz-2023
Unisource
Whatsapp
Zion
"""
formatted = ', '.join(f"'{name.strip()}'" for name in names.strip(). splitlines())
print(formatted)